#!/usr/bin/env node

var util  = require('util'),
    path  = require('path'),
    fs    = require('fs'),
    spawn = require('child_process').spawn,
    paths = [ '-v' ];

(function ls( tests_path ) {
  var stats = fs.statSync( tests_path );

  if ( stats.isDirectory() ) {
    fs.readdirSync( tests_path ).forEach( function( file ) {
      ls( path.join( tests_path, file ) );
    }, this );
}
  else if ( stats.isFile() ) paths.push( tests_path );

})( path.join( __dirname, 'units' ) );

var vows  = spawn( path.resolve( __dirname, '../node_modules/vows/bin/vows' ), paths );

vows.stdout.pipe( process.stdout );
vows.stderr.pipe( process.stderr );